### ISSUE TITLE
Unable to install. ModuleNotFoundError

### ISSUE THREAD

**Issue by vlongle** [h2r/pomdp-py#15]
Hi,
I'm following the instruction on https://h2r.github.io/pomdp-py/html/installation.html by cloning from Git, and `pip install -e .` but when I tried to run the example `python -m pomdp_problems.tiger.tiger_problem`.  I ran into this ModuleNotFound problem.
![Screen Shot 2021-08-01 at 11 44 36 PM](https://user-images.githubusercontent.com/37346413/127801682-6da5ed84-12fb-43df-8712-f9f12f2a87d4.png)

I ran into this issue with both Python 3.7 and 3.8 (using conda virtual envs). Thanks.

**Comment by zkytony** [comment]
Thanks for the report. I think the issue is with building the extensions in `setup.py`. I didn't built for individual Cython files (like `basics.pyx`) but only built at the directory level (`pomdp_py.framework`). Somehow it works when you do `pip install pomdp-py`, but not when you install it as a developer. Will fix this soon.

**Comment by zkytony** [comment]
Try now?

**Comment by vlongle** [comment]
It works now! Thank you for your fast response.
