### ISSUE TITLE
PO-UCT rollout not terminated after reaching goal state

### ISSUE THREAD

**Issue by jasonxyliu** [h2r/pomdp-py#8]
Hi,

In POMCP, the rollout terminates when either maximum depth or a goal state is reached. For a reference, please see line 327 of mcts.cpp.

I wonder if you need a check at the end of the while loop in po_uct.rollout
```
if state.terminal: 
    break 
```

To reproduce the bug, please create a RockSample(1, 0), change one of the default arguments of POMCP, max_depth=10000.

It is probably not a severe bug for your particular implementation of RSRewardModel.sample in terms of getting the correct action values because transitioning into exit area again after already in the exit area receives 0 reward. Also in the case where state space is large and max_depth is small, max_depth is likely to be reached before a goal state. But it is nice to not have to run many iterations of rollouts when it is not necessary, and possibly important for a different reward implementation.

Thank you!

**Comment by zkytony** [comment]
Thanks for the report.

What's the difference between terminating during PO-UCT rollout versus having a reward model that only returns 0 reward after reaching the terminal state?

I didn't include that in the PO-UCT because it's not always the case that there is a terminal state in POMDPs (it's not part of the standard definition). You may have terminal states in some domains, like rock sample, but for domains like Tiger, the domain description explicitly says that after you open the door, the game resets (instead of terminates).

**Comment by zkytony** [comment]
If you desire the behavior of terminating rollout after reaching terminal state, I think right now you could create a child class of POUCT and implement this behavior for your domain.
